version: '2'
services:
    db:
        restart: always
        image: 'tutum/influxdb:0.13'
        ports:
            - '8086'
            - '8083'
        volumes:
            - '/opt/influxdb/shared/data/db:/data'
        environment:
            PRE_CREATE_DB: 'faucet'
            ADMIN_USER: 'faucet'
            INFLUXDB_INIT_PWD: 'faucet'

    couchdb:
        restart: always
        image: 'couchdb:1.6'
        volumes:
            - './vol/opt/couchdb:/usr/local/var/lib/couchdb'
        environment:
            COUCHDB_USER: 'couch'
            COUCHDB_PASSWORD: '123'

    grafana:
        restart: always
        image: 'grafana/grafana:3.1.1'
        ports:
            - '3000:3000'
        volumes:
            - '/opt/grafana:/var/lib/grafana'
        links:
            - db

    gauge:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile.gauge
        image: 'faucet/gauge:latest'
        environment:
           - GAUGE_CONFIG=/etc/ryu/faucet/gauge.yaml
        volumes:
            - '/var/log/ryu/faucet:/var/log/ryu/faucet'
            - '/etc/ryu/faucet:/etc/ryu/faucet'
        ports:
            - '6634:6633'
        links:
            - couchdb
            - db

    faucet:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        image: 'faucet/faucet:latest'
        volumes:
            - '/var/log/ryu/faucet:/var/log/ryu/faucet'
            - '/etc/ryu/faucet:/etc/ryu/faucet'
        ports:
            - '6633:6633'

